In [1]:
from PandasUtils import PandasUtils as cpd
import pandas as pd
import time

In [2]:
actual_file_path = r'C://Desktop//Comparison//data//actual//'
expected_file_path = r'C://Desktop//Comparison//data//baseline//'

In [3]:
expected_file_name = '100_Sales_Records'
actual_file_name = '100_Sales_Records_1'
file_format = 'csv'
key_columns = ['Region', 'Country', 'Item_Type', 'Sales_Channel', 'Order_Priority', 'Order_Date']
# key_columns = ['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority', 'Order Date']
ignore_columns = ['Unit_Price', 'Total_Revenue']

In [4]:
start = time.time()
exec_summary_df, dup_cons_df, key_matched_df, key_mismatch_df, cell_cmp_df = cpd.df_diff(actual_file_path, expected_file_path,
                                                                        actual_file_name, expected_file_name,
                                                                        file_format, key_columns, ignore_columns)
print(str((time.time() - start)))
print(str((time.time() - start)/60))

****************************************************************************************************
PandasUtil Data Frame Comparison - Cell by Cell comparison with detailed mismatch report
****************************************************************************************************
Step-01 : Based on file format create the data frames with delimiter(sep)
Step-02 : Remove the columns based on ignore columns list
Step-03 : Check for duplicate rows in both actual and expected
Step-04 : Remove duplicate records from actual and expected
Step-05 : Sort the actual and expected based on key columns and reset the index
Step-06 : Identify the rows matching based on key in both actual and expected
Step-07 : Create the summary report based on count diff, duplicate rows and key mismatches
Step-08 : Remove the mismatched key values and proceed further in validation
Step-09 : Started cell by cell comparison for key values that exist in both actual and expected
Step-10 : Verify column data types in both the files, if not convert based on actual
Step-11 : Verify cell by cell data in both the data frame and generate mismatch report
          Failed : Cell by Cell comparison ..Started to extract mismatched column values
Step-12 : Comparison completed and generated info for reports(summary, keys mismatch, cell by cell
****************************************************************************************************

0.5953428745269775
0.009941947460174561

In [5]:
exec_summary_df

         Summary Expected Actual Mismatch
0  Total_Records       89    100      -11
1     Duplicates        0     10        0
2   Key_Mismatch        9     10        0

In [6]:
dup_cons_df

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Order_Date,Order_ID,Ship_Date,Units_Sold,Unit_Cost,Total_Cost,Total_Profit,source
0,Asia,Sri Lanka,Fruits,Online,L,11/7/11,830192887,12/18/11,0,6.92,9542.68,3323.39,Actual
1,Australia and Oceania,Papua New Guinea,Meat,Offline,M,5/15/15,940995585,6/4/15,0,364.69,131288.4,20592,Actual
2,Europe,Slovakia,Beverages,Offline,L,10/26/16,174590194,12/4/16,0,31.79,126301.67,62217.18,Actual
3,Middle East and North Africa,Morocco,Clothes,Online,M,9/14/13,667593514,10/19/13,0,35.84,165258.24,338631.84,Actual
4,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,5/17/17,880811536,7/2/17,0,35.84,20142.08,41273.28,Actual
5,Sub-Saharan Africa,Ghana,Office Supplies,Online,L,3/23/17,601245963,4/15/17,0,524.96,470364.16,113120,Actual
6,Sub-Saharan Africa,Seychelles,Beverages,Online,M,1/18/13,425793445,2/16/13,0,31.79,18978.63,9349.02,Actual
7,Sub-Saharan Africa,South Africa,Fruits,Offline,M,7/27/12,443368995,7/28/12,0,6.92,11023.56,3839.13,Actual
8,Sub-Saharan Africa,Tanzania,Beverages,Online,L,11/30/16,659878194,1/16/17,0,31.79,46922.04,23114.16,Actual
9,Sub-Saharan Africa,Tanzania,Cosmetics,Offline,L,5/23/16,739008080,5/24/16,0,263.33,2045547.44,1350622.16,Actual

In [7]:
len(key_matched_df)

80

In [8]:
key_matched_df

                                                                                      Order_ID_x  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13     153842341
                   India      Snacks          Online        L              10/10/12    440306556
                   Indonesia  Household       Online        C              9/28/11     520480573
                              Personal Care   Offline       L              10/22/12    678896129
                   Japan      Household       Offline       M              7/16/14     747796285
...                                                                                          ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14    156530129
                   The Gambia Fruits          Online        C              11/20/11    862861335
                   Togo       Cosmetics       Online        M              9/8/15      563681733
                   Uganda     Personal Care   Online        M              6/19/14     539471471
                   Zimbabwe   Office Supplies Offline       C              3/28/11     953361213

                                                                                      Ship_Date_x  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13        7/16/13
                   India      Snacks          Online        L              10/10/12      11/20/12
                   Indonesia  Household       Online        C              9/28/11        9/28/11
                              Personal Care   Offline       L              10/22/12      10/31/12
                   Japan      Household       Offline       M              7/16/14        7/24/14
...                                                                                           ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14      11/29/14
                   The Gambia Fruits          Online        C              11/20/11      11/22/11
                   Togo       Cosmetics       Online        M              9/8/15          9/9/15
                   Uganda     Personal Care   Online        M              6/19/14        7/21/14
                   Zimbabwe   Office Supplies Offline       C              3/28/11         4/8/11

                                                                                      Units_Sold_x  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13               0
                   India      Snacks          Online        L              10/10/12              0
                   Indonesia  Household       Online        C              9/28/11               0
                              Personal Care   Offline       L              10/22/12              0
                   Japan      Household       Offline       M              7/16/14               0
...                                                                                            ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14              0
                   The Gambia Fruits          Online        C              11/20/11              0
                   Togo       Cosmetics       Online        M              9/8/15                0
                   Uganda     Personal Care   Online        M              6/19/14               0
                   Zimbabwe   Office Supplies Offline       C              3/28/11               0

                                                                                      Unit_Cost_x  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13         117.11
                   India      Snacks          Online        L              10/10/12         97.44
                   Indonesia  Household       Online        C              9/28/11         502.54
                              Personal Care   Offline       L              10/22/12         56.67
                   Japan      Household       Offline       M              7/16/14         502.54
...                                                                                           ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14          6.92
                   The Gambia Fruits          Online        C              11/20/11          6.92
                   Togo       Cosmetics       Online        M              9/8/15          263.33
                   Uganda     Personal Care   Online        M              6/19/14          56.67
                   Zimbabwe   Office Supplies Offline       C              3/28/11         524.96

                                                                                      Total_Cost_x  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13       494438.42
                   India      Snacks          Online        L              10/10/12      521206.56
                   Indonesia  Household       Online        C              9/28/11       313082.42
                              Personal Care   Offline       L              10/22/12      527371.02
                   Japan      Household       Offline       M              7/16/14      4217818.22
...                                                                                            ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14       66425.08
                   The Gambia Fruits          Online        C              11/20/11       60197.08
                   Togo       Cosmetics       Online        M              9/8/15       1265563.98
                   Uganda     Personal Care   Online        M              6/19/14        25558.17
                   Zimbabwe   Office Supplies Offline       C              3/28/11      5051690.08

                                                                                      Total_Profit_x  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13         374026.98
                   India      Snacks          Online        L              10/10/12        294943.86
                   Indonesia  Household       Online        C              9/28/11         103249.79
                              Personal Care   Offline       L              10/22/12        233208.36
                   Japan      Household       Offline       M              7/16/14        1390971.89
...                                                                                              ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14         23133.59
                   The Gambia Fruits          Online        C              11/20/11         20964.59
                   Togo       Cosmetics       Online        M              9/8/15          835619.22
                   Uganda     Personal Care   Online        M              6/19/14          11302.06
                   Zimbabwe   Office Supplies Offline       C              3/28/11        1214903.75

                                                                                      Order_ID_y  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13     153842341
                   India      Snacks          Online        L              10/10/12    440306556
                   Indonesia  Household       Online        C              9/28/11     520480573
                              Personal Care   Offline       L              10/22/12    678896129
                   Japan      Household       Offline       M              7/16/14     747796285
...                                                                                          ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14    156530129
                   The Gambia Fruits          Online        C              11/20/11    862861335
                   Togo       Cosmetics       Online        M              9/8/15      563681733
                   Uganda     Personal Care   Online        M              6/19/14     539471471
                   Zimbabwe   Office Supplies Offline       C              3/28/11     953361213

                                                                                      Ship_Date_y  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13        7/16/13
                   India      Snacks          Online        L              10/10/12      11/20/12
                   Indonesia  Household       Online        C              9/28/11        9/28/11
                              Personal Care   Offline       L              10/22/12      10/31/12
                   Japan      Household       Offline       M              7/16/14        7/24/14
...                                                                                           ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14      11/29/14
                   The Gambia Fruits          Online        C              11/20/11      11/22/11
                   Togo       Cosmetics       Online        M              9/8/15          9/9/15
                   Uganda     Personal Care   Online        M              6/19/14        7/21/14
                   Zimbabwe   Office Supplies Offline       C              3/28/11         4/8/11

                                                                                      Units_Sold_y  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13               0
                   India      Snacks          Online        L              10/10/12              0
                   Indonesia  Household       Online        C              9/28/11               0
                              Personal Care   Offline       L              10/22/12              0
                   Japan      Household       Offline       M              7/16/14               0
...                                                                                            ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14              0
                   The Gambia Fruits          Online        C              11/20/11              0
                   Togo       Cosmetics       Online        M              9/8/15                0
                   Uganda     Personal Care   Online        M              6/19/14               0
                   Zimbabwe   Office Supplies Offline       C              3/28/11               0

                                                                                      Unit_Cost_y  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13         127.11
                   India      Snacks          Online        L              10/10/12         97.44
                   Indonesia  Household       Online        C              9/28/11         502.54
                              Personal Care   Offline       L              10/22/12         56.67
                   Japan      Household       Offline       M              7/16/14         502.54
...                                                                                           ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14          6.92
                   The Gambia Fruits          Online        C              11/20/11          6.92
                   Togo       Cosmetics       Online        M              9/8/15          263.33
                   Uganda     Personal Care   Online        M              6/19/14          56.67
                   Zimbabwe   Office Supplies Offline       C              3/28/11         524.96

                                                                                      Total_Cost_y  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13       494438.42
                   India      Snacks          Online        L              10/10/12      521206.56
                   Indonesia  Household       Online        C              9/28/11       313082.42
                              Personal Care   Offline       L              10/22/12      527371.02
                   Japan      Household       Offline       M              7/16/14      4217818.22
...                                                                                            ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14       66425.08
                   The Gambia Fruits          Online        C              11/20/11       60197.08
                   Togo       Cosmetics       Online        M              9/8/15       1265563.98
                   Uganda     Personal Care   Online        M              6/19/14        25558.17
                   Zimbabwe   Office Supplies Offline       C              3/28/11      5051690.08

                                                                                      Total_Profit_y  \
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13         374026.98
                   India      Snacks          Online        L              10/10/12        294943.86
                   Indonesia  Household       Online        C              9/28/11         103249.79
                              Personal Care   Offline       L              10/22/12        233208.36
                   Japan      Household       Offline       M              7/16/14        1390971.89
...                                                                                              ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14         23133.59
                   The Gambia Fruits          Online        C              11/20/11         20964.59
                   Togo       Cosmetics       Online        M              9/8/15          835619.22
                   Uganda     Personal Care   Online        M              6/19/14          11302.06
                   Zimbabwe   Office Supplies Offline       C              3/28/11        1214903.75

                                                                                      source
Region             Country    Item_Type       Sales_Channel Order_Priority Order_Date
Asia               Brunei     Cereal          Offline       L              5/28/13      both
                   India      Snacks          Online        L              10/10/12     both
                   Indonesia  Household       Online        C              9/28/11      both
                              Personal Care   Offline       L              10/22/12     both
                   Japan      Household       Offline       M              7/16/14      both
...                                                                                      ...
Sub-Saharan Africa Tanzania   Fruits          Offline       H              10/20/14     both
                   The Gambia Fruits          Online        C              11/20/11     both
                   Togo       Cosmetics       Online        M              9/8/15       both
                   Uganda     Personal Care   Online        M              6/19/14      both
                   Zimbabwe   Office Supplies Offline       C              3/28/11      both

[80 rows x 13 columns]

In [9]:
key_mismatch_df

                                                                                                                                source
Region                            Country                          Item_Type       Sales_Channel Order_Priority Order_Date
Asia                              Turkmenistan                     Meat            Online        M              4/30/17      left_only
Australia and Oceania             New Zealand                      Beverages       Online        M              10/11/12     left_only
                                  Vanuatu                          Cereal          Offline       C              6/20/14      left_only
Middle East and North Africa      Pakistan                         Meat            Online        M              12/28/13     left_only
North America                     United States of America         Personal Care   Online        H              1/21/16      left_only
Sub-Saharan Africa                Democratic Republic of the Congo Cosmetics       Online        M              10/7/12      left_only
                                  Liberia                          Baby Food       Offline       H              6/6/15       left_only
                                  Madagascar                       Clothes         Online        L              10/17/16     left_only
                                  Malawi                           Meat            Offline       H              3/1/16       left_only
Asia                              China                            Office Supplies Online        M              2/10/16     right_only
                                  Turkmenistan                     Vegetables      Online        M              4/13/15     right_only
Central America and the Caribbean Dominican Republic               Baby Food       Offline       H              8/25/11     right_only
                                  Haiti                            Office Supplies Online        C              12/31/10    right_only
                                  Nicaragua                        Household       Online        C              10/28/15    right_only
                                  The Bahamas                      Personal Care   Online        C              1/19/11     right_only
Europe                            United Kingdom                   Cosmetics       Online        L              5/1/15      right_only
Middle East and North Africa      Kuwait                           Household       Offline       C              6/13/11     right_only
                                  United Arab Emirates             Office Supplies Online        M              6/23/12     right_only
Sub-Saharan Africa                Uganda                           Cosmetics       Online        M              2/28/15     right_only

In [10]:
cell_cmp_df

,,,,,,,Expected_Data,Actual_Data
Region,Country,Item_Type,Sales_Channel,Order_Priority,Order_Date,Mismatch_Column,,
Asia,Brunei,Cereal,Offline,L,5/28/13,Unit_Cost,117.11,127.11